### PR TITLE
Add date/time localized format and translated tooltips to Datepicker

### PR DESCRIPTION
**Pull request by Ravaelles**
**Major changes:**
- Added month selector
- Added tooltips to control buttons
- Can now use translated tooltips for buttons (e.g. prev / next month)
- Can now display date and time in localized format (`2019/14/02 11:55pm` or `14.02.2019 23:55` etc), date formatting is handled by `formatter` which is passed a prop
- Added AM/PM selector to hour selector
- Date being emitted is always using `YYYY-MM-DD (HH:MM)` format

**Minor changes:**
- CSS improvements (made buttons slightly bigger)
- refactored order of props
- updated the docs

### CODE REVIEW

**Comment by Ravaelles** [comment]
[(4) Add translations to Date and DateTime fields](https://trello.com/c/loqloXYL/2763-4-add-translations-to-date-and-datetime-fields)

**Comment by Ravaelles** [comment]
[(4) Datetime field [16]](https://trello.com/c/gOVv5qwe/2683-4-datetime-field-16)

**Comment by Ravaelles** [comment]
Hey, @antennaio, which test was it that was failing in your case? On my end they all pass:

image

**Comment by antennaio** [comment]
FAILED TESTS:
  Datepicker
    ✖ should format date

It's `TypeError: Cannot read property 'getHours' of undefined` when I run tests on the `vue-bootstrap` project. @Ravaelles

**Comment by antennaio** [comment]
Thanks @Ravaelles - the tests are passing, but I still see the warnings. The problem is that the `value` prop is optional, but then the first thing the component does is try to parse and later format it in the `created()` hook:

```
this.date = this.parseDate(this.value);
this.dateInput = this.formatDateTime(this.date);
```

For all we know `this.value` could be empty.

You can see the problem by updating the example in the docs and skipping the value:
`<datepicker value="" mode="datetime"></datepicker>`

The component should work fine without any initial value provided.

We'd be running into this problem very soon... On Falcon the datepicker is used to enter the start date for an account. Very often the start date isn't set at all. And there needs to be a way to set it without providing the initial `value`.

**Comment by Ravaelles** [comment]
@antennaio Thanks for pointing out the problem with empty date. There was plenty of work with allowing it, but obviously this was incredibly important functionality + I was able to find one bug with month selector not working properly + another bug with time validator not working due to having leading space.

All fixed now, tests are passing & tested manually.

**Pull request merged**
